### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by daidr** [aFlyBird0/blog-friends#10]
### 站点名字

戴兜的小屋

### 站点地址

https://im.daidr.me

### 站点描述

Coding the world.

### 站点图标或个人头像

https://gravatar.loli.net/avatar/ae60929569d79ff0464c51e1aaea4be8?s=512&d=mm&r=g

### 主题色

None

### 头像动画

None

### 边框动画

None

**Comment by aFlyBird0** [comment]
合并啦合并啦！又捕获一个佬！
