### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by GoldenSheep402** [aFlyBird0/blog-friends#12]
### 站点名字

金羊的部落阁

### 站点地址

https://www.glodensheep.top/

### 站点描述

在对人类的抽象的爱中，能爱的几乎永远是自己一个人。

### 站点图标或个人头像

https://thirdqq.qlogo.cn/g?b=sdk&k=4vMtghkUUYLCic2AIic86lzQ&s=640

### 主题色

None

### 头像动画

None

### 边框动画

None

### 还有什么其他想说的吗❤️

你好呀，鸟鸟~

**Comment by aFlyBird0** [comment]
你好呀，金羊~友链已经加上啦 https://blog.aflybird.cn/friends/
