### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by chengsecret** [aFlyBird0/blog-friends#13]
### 站点名字

燎原的博客

### 站点地址

https://blog.koisecret.site/

### 站点描述

翻更高的山，见更美的风景

### 站点图标或个人头像

https://avatars.githubusercontent.com/u/51410717?s=400&u=06a1f1df85dcea98652c12950e6d10747be8cb2a&v=4

### 主题色

None

### 头像动画

None

### 边框动画

None

**Comment by aFlyBird0** [comment]
OKOK！已经在自动走流程了！🚀
