### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by IndigoVoid** [aFlyBird0/blog-friends#14]
### 站点名字

indigovoid

### 站点地址

https://indigovoid.github.io/

### 站点描述

-

### 站点图标或个人头像

https://indigovoid.github.io/images/avatar.jpg

### 友链分组（可自定义）

盆友

### 主题色

linear-blue

### 头像动画

None

### 边框动画

shadow

**Comment by aFlyBird0** [comment]
我配置的 GitHub Actions 的 secret 过期了，等我调试一下！

**Comment by aFlyBird0** [comment]
可以啦！
