### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by zzzlight** [aFlyBird0/blog-friends#15]
### 站点名字

zzzlight的博客

### 站点地址

https://www.cnblogs.com/zzzlight

### 站点描述

zzzlight的个人博客，现在只有技术，以后可能啥都会有

### 站点图标或个人头像

https://pic.cnblogs.com/avatar/1808333/20220803165039.png

### 主题色

None

### 头像动画

None

### 边框动画

None

### 还有什么其他想说的吗❤️

自己写的那个网站太不稳定了，放上博客园的友链，以后没事在博客园先更新。

**Comment by aFlyBird0** [comment]
合并了，等CI/CD跑完就OK了。
预览链接：https://brave-tree-04055d800-16.eastasia.1.azurestaticapps.net/friends/
