### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by fzf404** [aFlyBird0/blog-friends#16]
### 站点名字

fzf404

### 站点地址

https://fzf404.art/

### 站点描述

🏳️‍🌈 全沾开发者 ✨ 白日梦想家

### 站点图标或个人头像

https://img.fzf404.art/avatar.webp

### 主题色

None

### 头像动画

None

### 边框动画

None

**Comment by aFlyBird0** [comment]
好啦。（正巧我博客也很久很久没更新了哈哈哈，你提醒了我该更新了
