### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by nickxudotme** [aFlyBird0/blog-friends#5]
### 站点名字

NX の 博客

### 站点地址

www.nickxu.top

### 站点描述

这家伙真勤奋，什么都留下了

### 站点图标或个人头像

https://www.nickxu.top/static/favicon.jpg

### 主题色

None

### 头像动画

rotate

### 边框动画

None

### 还有什么其他想说的吗❤️

新的 issue form 有那么一点让我眼前一亮（

**Comment by aFlyBird0** [comment]
> ### 站点名字
> 
> NX の 博客
> 
> ### 站点地址
> 
> www.nickxu.top
> 
> ### 站点描述
> 
> 这家伙真勤奋，什么都留下了
> 
> ### 站点图标或个人头像
> 
> https://www.nickxu.top/static/favicon.jpg
> 
> ### 友链分组（可自定义）
> 
> _No response_
> 
> ### 主题色
> 
> None
> 
> ### 头像动画
> 
> rotate
> 
> ### 边框动画
> 
> None
> 
> ### 还有什么其他想说的吗❤️
> 
> 新的 issue form 有那么一点让我眼前一亮（

收到收到！感谢NX哈哈哈，终于有友链了！新的issue表单确实好用，就是提取内容的时候好像没有api，得自己正则什么的。  马上合并PR！
