### ISSUE TITLE
“你什么档次？跟我用一个代码托管平台？！”

### ISSUE THREAD

**Issue by rsyanting** [aFlyBird0/blog-friends#6]
[不知所云 的博客](https://blog.ryantech.ltd/)

**Comment by aFlyBird0** [comment]
> [不知所云 的博客](https://blog.ryantech.ltd/)

收到！😍

是我高攀了555

**Comment by rsyanting** [comment]
> > [不知所云 的博客](https://blog.ryantech.ltd/)
> 
> 收到！😍
> 
> 是我高攀了555

“出来留学这么多年，花了这么多钱，我为了什么，不就是为了搞个博客！”

**Comment by aFlyBird0** [comment]
已加 https://blog.aflybird.cn/friends/
