### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by violetjam** [aFlyBird0/blog-friends#7]
### 站点名字

violet

### 站点地址

violetjam.github.io

### 站点描述

Violet I Personal blog

### 站点图标或个人头像

https://violetjam.github.io/images/author.jpg

### 友链分组（可自定义）

盆友

### 主题色

default

### 头像动画

rotate

### 边框动画

None

**Comment by aFlyBird0** [comment]
收到啦收到啦！
