### ISSUE TITLE
申请友链: 

### ISSUE THREAD

**Issue by psyq55262227** [aFlyBird0/blog-friends#9]
### 站点名字

psyqLK的日常

### 站点地址

blog.psyqlk.space

### 站点描述

生有热烈，藏与俗常

### 站点图标或个人头像

https://thirdqq.qlogo.cn/g?b=sdk&k=vFCLPytxmpqlzpxG55pdyw&s=640

### 主题色

None

### 头像动画

None

### 边框动画

None

**Comment by aFlyBird0** [comment]
收到收到！已经在拿着小鞭子让GitHub和Azure帮我部署博客啦！
